#!/usr/bin/env bash
# Regenerate .env for the production deployment from Azure Key Vault.
# Key Vault: kv-bronxtc-dev, namespace midas--production--*  (single source of truth).
# Usage: ./deploy/fetch-env.sh   then:  sudo docker compose -f deploy/docker-compose.yml up -d
set -euo pipefail

VAULT="kv-bronxtc-dev"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.env"

get() { az keyvault secret show --vault-name "$VAULT" -n "midas--production--$1" --query value -o tsv 2>/dev/null || true; }

ANTHROPIC_API_KEY="$(get ANTHROPIC-API-KEY)"
if [ -z "$ANTHROPIC_API_KEY" ]; then
  echo "ERROR: midas--production--ANTHROPIC-API-KEY not found in $VAULT." >&2
  exit 1
fi

# Sentry DSN is optional in v1 — empty string is fine, do not fail the script.
SENTRY_DSN="$(get SENTRY-DSN)"

# GH_TOKEN: prefer the fine-grained PAT scoped to allowlist repos; fall back to the
# host's broad gh CLI token (least-privilege challenge #1.4 in the backlog) with a
# loud warning so the fallback doesn't go unnoticed.
GH_TOKEN="$(get GH-TOKEN)"
if [ -z "$GH_TOKEN" ]; then
  echo "WARN: midas--production--GH-TOKEN not set; using broad gh host token, issue a fine-grained PAT" >&2
  GH_TOKEN="$(gh auth token)"
fi

umask 077
cat > "$ENV_FILE" <<EOF
# GENERATED by deploy/fetch-env.sh from Azure Key Vault $VAULT (namespace midas--production--*).
# Do NOT edit by hand and do NOT commit. To rotate, update Key Vault then re-run this script.
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
GH_TOKEN=$GH_TOKEN
SENTRY_DSN=$SENTRY_DSN
EOF
chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE (mode 600) from Key Vault $VAULT."
